# Generated by Django 3.1 on 2020-08-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
