# Generated by Django 3.1 on 2020-08-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0002_auto_20200820_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'ordering': ['name'], 'verbose_name': 'book genre', 'verbose_name_plural': 'book genres'},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'verbose_name': 'book review', 'verbose_name_plural': 'book reviews'},
        ),
    ]
