# Generated by Django 3.1 on 2020-08-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0003_auto_20200821_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
