# Generated by Django 3.1 on 2020-08-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0004_auto_20200821_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
