# Generated by Django 3.1 on 2020-08-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200819_2225'),
        ('book_functionalities', '0005_auto_20200821_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='user',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
