# Generated by Django 3.1 on 2020-08-22 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0006_auto_20200822_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
