# Generated by Django 3.1 on 2020-08-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0007_bookreview_creation_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='score',
            new_name='rating',
        ),
    ]
