# Generated by Django 3.1 on 2020-08-22 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0008_auto_20200822_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name=django.core.validators.MaxValueValidator(10, message="The score can't be higher than 10")),
        ),
    ]
