# Generated by Django 3.1 on 2020-08-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200819_2225'),
        ('book_functionalities', '0009_auto_20200822_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('user_profile', 'book')},
        ),
    ]
