# Generated by Django 3.1 on 2020-08-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0010_auto_20200822_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
