# Generated by Django 3.1 on 2020-08-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0012_auto_20200822_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='title',
        ),
    ]
