# Generated by Django 3.1 on 2020-08-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200819_2225'),
        ('book_functionalities', '0015_auto_20200823_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_book', to='book_functionalities.book')),
                ('recommended_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_book', to='book_functionalities.book')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'book recommendation',
                'verbose_name_plural': 'book recommendations',
                'ordering': ['base_book', 'recommended_book'],
                'unique_together': {('user_profile', 'base_book', 'recommended_book')},
            },
        ),
    ]
