# Generated by Django 3.1 on 2020-08-23 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0016_bookrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 23, 19, 40, 19, 549304, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
