# Generated by Django 3.1 on 2020-08-23 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0017_bookrecommendation_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, message="The score can't be higher than 10")]),
        ),
    ]
