# Generated by Django 3.1 on 2020-08-27 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20200826_1905'),
        ('book_functionalities', '0023_auto_20200827_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='user_profile.userprofile'),
        ),
    ]
