# Generated by Django 3.1 on 2020-08-28 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0025_auto_20200828_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['book', '-rating'], 'verbose_name': 'book review', 'verbose_name_plural': 'book reviews'},
        ),
    ]
