# Generated by Django 3.1 on 2020-08-30 18:45

import book_functionalities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0026_auto_20200828_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(validators=[book_functionalities.models.no_future_dates_validator]),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(validators=[book_functionalities.models.no_future_dates_validator]),
        ),
    ]
