# Generated by Django 3.1 on 2020-08-30 19:01

import book_functionalities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0027_auto_20200830_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(validators=[book_functionalities.models.date_is_past]),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(validators=[book_functionalities.models.date_is_past]),
        ),
    ]
