# Generated by Django 3.1 on 2020-08-31 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0029_auto_20200830_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, message="The rating can't be higher than 10"), django.core.validators.MinValueValidator(1, message="The rating can't be lower than 1")]),
        ),
    ]
