# Generated by Django 3.1 on 2020-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_functionalities', '0030_auto_20200831_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
