# Generated by Django 3.1 on 2020-08-19 21:15

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200818_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_pic', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
