# Generated by Django 3.1 on 2020-08-19 21:18

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='profile_picture'),
        ),
    ]
