# Generated by Django 3.1 on 2020-08-19 21:27

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200819_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_picture', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
