# Generated by Django 3.1 on 2020-08-19 22:01

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20200819_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='profile_picture'),
        ),
    ]
