# Generated by Django 3.1 on 2020-08-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_userprofilefollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
